Concept
OSLL/adfmp19-map-marks pull request #1
Opened 2019-02-26 10:50 UTC by AlexVanGogen

2019-03-04 20:15 UTC, cripson1994 commented
@AlexVanGogen Я сам исправил замечания, проверь их https://github.com/OSLL/adfmp19-map-marks/pull/2 и если всё ок, то будем мёрджить в мастер. Но на вопросы в этом пул-реквесте всё равно ответь - есть что обсудить.

2019-03-04 21:34 UTC, cripson1994 requested changes

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/data/category/Category.kt
> +class Category(
Почему не data class?

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/data/mark/Mark.kt
> +class Mark(
data class?

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/prototype/DummyMarkInfoContainer.kt
> +        Mark("BUSINESS LUNCH", "Самый примитивный обед", categories[2], MarkerOptions().position(randomLatLng()))
Это временное решение?

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/res/layout/activity_add_mark.xml
> +</android.support.constraint.ConstraintLayout>
Скрины создания метки и категории практически не отличаются, зачем для каждой из них создавать свой layout?

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/AddCategoryActivity.kt
> +        val addCategoryDescriptionEdit = findViewById<TextInputEditText>(R.id.add_category_description)
по моему проще заменить кучу find'ов на один import: 
`import kotlinx.android.synthetic.main.activity_add_category.*`

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/AddMarkActivity.kt
> +            val addMarkDescriptionEdit = findViewById<TextInputEditText>(R.id.add_mark_description)
то же самое

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/MainScreenActivity.kt
> +        val markDistanceView = markInfoSheetLayout.findViewById<TextView>(R.id.mark_info_mark_distance)
то же

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/data/mark/MarkDataWriter.kt
> +interface MarkDataWriter {
Я не очень понял зачем нужен этот интерфейс?

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/data/mark/GsonMarkDataWriter.kt
> +class GsonMarkDataWriter: MarkDataWriter {
И почему Gson, а не Json?

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/MyMarksActivity.kt
> +class MyMarksActivity : AppCompatActivity() {
MyMarksActivity и MyCategoriesActivity очень сильно похожи, не унаследовать ли их от одного и того-же класса, чтобы исключить большое копирование кода

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/MyCategoriesViewAdapter.kt
> +class MyCategoriesViewAdapter(val allCategories: List<Category>, val context: Context): RecyclerView.Adapter<MyCategoriesViewAdapter.MyCategoriesViewHolder>() {
Тоже очень похож на CategoryMarksViewAdapter, может тоже подумать над тем, чтобы убрать копирование кода Объектно-Ориентированными способами?

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/MainScreenActivity.kt
> +        markLocationPlaceView.text = "Пенза, РФ"
Я не очень понял что это за поле и какую информацию оно должно содержать

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/MainScreenActivity.kt
> +        }
Не понял, что делает этот обработчик, если он должен закрывать попап с информацией о метке, по нажатию на пустое пространство, то это не работает

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/MainScreenActivity.kt
> +        }
Не понял что тут происходит. Выбранная метка должна подсветиться жёлтым и камера перепрыгнуть на неё?

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/MainScreenActivity.kt
> +    private lateinit var map: GoogleMap
Почему эта переменная вынесена в поля класса, если она используется только в одном методе onMapReady, где же и инициализируется

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/MainScreenActivity.kt
> +    private lateinit var mainView: CoordinatorLayout
А что будет, если её вовсе убрать? (не понял зачем она тут вообще нужна)

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/data/storage/MarkInfoContainer.kt
> +    val allMarks: Iterable<Mark>
Почему в MarkInfoContainer лежат ещё и категории? Может для них тоже лучше сделать CategoryInfoContainer

2019-03-04 21:34 UTC, cripson1994 commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/CategoryMarksActivity.kt
> +class CategoryMarksActivity : AppCompatActivity() {
Вообще не понял зачем нужна эта Активити, почему не переиспользовать MyMarksActivity?

2019-03-05 22:02 UTC, AlexVanGogen commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/data/category/Category.kt
> +class Category(
equals/hashcode не по всем свойствам

2019-03-05 22:02 UTC, AlexVanGogen commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/data/category/Category.kt
> +class Category(
equals/hashcode не по всем свойствам

2019-03-05 22:04 UTC, AlexVanGogen commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/MainScreenActivity.kt
> +        markLocationPlaceView.text = "Пенза, РФ"
См. #13

2019-03-05 22:05 UTC, AlexVanGogen commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/data/storage/MarkInfoContainer.kt
> +    val allMarks: Iterable<Mark>
См. #5

2019-03-05 22:07 UTC, AlexVanGogen commented on MapMarks/app/src/main/java/ru/itmo/se/mapmarks/data/mark/MarkDataWriter.kt
> +interface MarkDataWriter {
См. #16

2019-03-10 18:32 UTC, closed without merging